### ISSUE TITLE
add config into moebius function metadata

### ISSUE THREAD

**Issue by BrunoBonacci** [samsara/samsara#41]

**Comment by DayoOliyide** [comment]
Could you explain a bit more about the config ?
I can see that in [samsara-core](https://github.com/samsara/samsara/blob/master/core/src/samsara_core/core.clj#L57) the core config looks like it's not being used when creating the samsara pipeline
```clojure
(defn make-samsara-pipeline [config]
  (pipeline
   inject-kibana-timestamp
   ;;is-timestamp-reliable
   inject-id
   ;;event-sequencer
   ))



(defn make-samsara-processor [config]
  (moebius (make-samsara-pipeline config)))
```

Do mean altering the required functions so that the config can be passed into the [`moebius-fn`](https://github.com/samsara/samsara/blob/master/moebius/src/moebius/core.clj#L174) ?

**Comment by BrunoBonacci** [comment]
The `make-*` take a generic configuration parameter that should be injected by the core when called.
In this case a processor function or module could be parametric based on some configuration parameters.

I had this idea that we could inject the configuration as part of the moebius functions as info.
In afterthoughts, I think this is actually a bad idea. I would make sense only for the modules, and probably not even in that case.
One idea was to base the modules infrastructure in sierra's component library. however I don't think this i a good idea either.

I think we should close this as the module subsystem need some serious thoughts, and this is not longer so relevant.
I'll close it for now, let me know if you want to discuss it further.
